#!/bin/sh

apt update
apt upgrade
apt install -y unzip
export TFLINT_VERSION=v0.46.1
curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | sed 's/unzip -u/unzip -o/' | bash
tflint --init
cd uri-default
tflint --no-color ${PLUGIN_FLAGS}
echo 'done with tflint'
